#!/bin/sh

set -e
umask 0002

OPTIONS="--show name --show-table name,driver,subdriver,protocol,bus,vendorid,productid --hostname name --select-base /usr/libexec/device/system/ups/usb/drivers.txt --select driver --select-base /usr/libexec/device/system/ups/usb/subdrivers.txt --select subdriver --select-base /usr/libexec/device/system/ups/usb/protocols.txt --select protocol --symlink-base /dev/bus/usb --symlink bus --hex-width 4 --hex-maximum FFFF --hex vendorid --hex-maximum FFFF --hex productid"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

